# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionToDo', '0002_auto_20180509_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='last_update',
            new_name='LastUpdate',
        ),
        migrations.RenameModel(
            old_name='ToDo_List',
            new_name='ToDoList',
        ),
    ]
