# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionToDo', '0003_auto_20180509_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
