# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionToDo', '0006_auto_20180510_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.CharField(max_length=50),
        ),
    ]
