# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionToDo', '0007_auto_20180510_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastupdate',
            old_name='update',
            new_name='lastUpdate',
        ),
    ]
